### ISSUE TITLE
Google Drive support?

### ISSUE THREAD

**Issue by ranjanan** [chriskol/Google-Docs-Desktop-OSX#2]
Hi, 

Thanks for the really useful app! 

Is it possible to do this with Google Drive as well?

**Comment by ranjanan** [comment]
Ah, I figured out a way. I just pointed to `drive.google.com` instead of `docs.google.com`. However, creating a new doc seems to want to open a new tab that opens up in the browser.

**Comment by chriskol** [comment]
This is actually a good idea and would help me a LOT with dealing with Drive since I refuse to sync it to my computer for HD space reasons and find it clunky in FireFox.

Also encountered the issue you had with the new document thing but don't have the time to fix it now.  Probably something around forcing targets to open within that window.

Closing this as per below and maybe we can pick up at the link below?

Made a new repo [here](https://github.com/chriskol/Google-Drive-Desktop-OSX)
